### PR TITLE
Update to version 1.5.3

### PR DESCRIPTION
**Pull request by Sjoerd1993**
It's about time to release the next version 1.5.3. 
There's some pretty ugly bugs in the current release state that I really want to get out and have been fixed. Having a nice stable version out now, also allows us to further focus on more experimental features such as adding new data types and fitting (see PR #246).  I will probably start on work with fitting data during the coming weeks. The hard parts are all solved by scipy, and I've done this from regular python code in the past. But the big challenge is more the design part.

Either way, this release adds a lot of good bug fixes. And some pretty good QoL changes with a more streamlined experience. The new localization is also good (adding three new languages at once) of course and noteworthy of highlighting. 

Once the release is out, I'll put out a post in the [TWIG](https://thisweek.gnome.org/) blog, giving us a spot on issue number 100. I'll also highlight the Snap package there as well, on top of the other changes. It usually also gets us featured in [the Linux Experiment](https://www.youtube.com/watch?v=Z26nueN8KPI&t=558s) as well, which is pretty neat.

If there's any other changes or fixes that ought to be in the next release, I can wait before actually merging this. The intention was to push the 1.5.3 release before friday evening, but there's no real hard deadlines here.

### CODE REVIEW

**Comment by Sjoerd1993** [comment]
On another note, @cmkohnen, do you want me to request Flathub to get access to the [Flathub repo](https://github.com/flathub/se.sjoerd.Graphs)? It's not like we push releases that often, but it would allow you to merge Flathub releases as well. 

Stable releases should first be pushed and tagged here, but you have my blessing to push stuff to beta in that case without consulting me either.

**Comment by cmkohnen** [comment]
On the top of my head I can't think of an issue or change, that can't be pushed to a later one. I'm fine with releasing.
I feel like with some changes releasing this as patch might not be fitting. 1.6.0 might be a better version.

Regarding flathub: I'd be happy to get access: In absolute emergency situations (critical issue in one dependency for example) either one of us can issue a fix.
Also introducing a co-review-process (at least on releases) should help spot issues beforehand

**Comment by Sjoerd1993** [comment]
> I feel like with some changes releasing this as patch might not be fitting. 1.6.0 might be a better version.

I've considered v1.6.0 as version number as well. That may make more sense, keeping the point releases to pure bug fixes and very minor changes. There's a number of changes in here that may not make sense as a patch.

I'll probably change that later when I'm at home again. Will also submit a PR to Flathub to add you as collaborator on the Flathub repo.

**Comment by cmkohnen** [comment]
After this release, we might consider applying for GNOME Circle.
I feel, the UI is in a good state at the moment and I'd only change the view menu slightly (New optimize feature and view back/forth buttons). Any changes required should in theory be applicable to patch releases.

**Comment by Sjoerd1993** [comment]
> After this release, we might consider applying for GNOME Circle.

I think that's a good goal to strive for yes. We should take a careful look again at all of the requirements, but I think we can start taking that step soon. I do feel like Graphs has it's place in the GNOME ecosystem.

**Comment by cmkohnen** [comment]
The appstream version has to be updated too

**Review by cmkohnen — APPROVED** [review]

**Pull request merged**
