### PR TITLE
Add curve fitting options

### PR DESCRIPTION
**Pull request by Sjoerd1993**
Adds the following options to the Curve Fitting dialog:

- **Equation**: Sets the equation that is currently used. I've set the default value to "Custom" for discoverability's sake, the idea there was that out of the box all entries are working and editable. Then when one discovers the setting, it is more obvious why this box is grayed out. The reason for not removing this box, is so that it's clear what the equation itself is that is being fitted to.
- **Optimization**: Sets the optimization algorithm that is being used for the fit. Typical Levenberg-Marquardt is the standard for most tools I've come across. But there may be reasons for prefering others.
- **Confidence bounds**: This sets the confidence bounds. Allowing this to turn them off, or to just set it to a multiple of the standard deviation. Which works well enough as a set of options for now at least.

Compared to the video below, I've removed the "Toggle Sidebar" option, as it seemed a bit unintuitive to actually use that in the dialog.

[Skärminspelning från 2023-12-19 09-58-44.webm](https://github.com/Sjoerd1993/Graphs/assets/68477016/db8bd2ef-6d9c-477d-9c08-098298db3a14)

Closes issue #494

### CODE REVIEW

**Comment by Sjoerd1993** [comment]
I think you're right. It's also more discoverable, and it gives an immediate look at the current setting. I was just slightly unsure as it would make the sidebar a bit taller by default, but that may be worth it.

**Comment by Sjoerd1993** [comment]
Have to think about how to do it nicely UI-wise. Just using an entry row will look like this. Perhaps it may be good to have it in a seperate group so there's some space in between, although it does make sense to couple them:

image

**Comment by Sjoerd1993** [comment]
So this now uses a comborow, where the subtitle is used to show the equation when a preset value is chosen.

[Skärminspelning från 2023-12-19 20-14-14.webm](https://github.com/Sjoerd1993/Graphs/assets/68477016/8f15a21d-8941-42b3-acc6-fb078a3967ca)

**Comment by Sjoerd1993** [comment]
So right now if I select an equation from the Comborow, that all works fine. But if I then close the dialog, and select an equation again, I get a crash. It seems to trigger the `on_select` signal twice for some reason, and never runs `set_equation`. I don't know why at this moment.

**Comment by Sjoerd1993** [comment]
Okay, the fix to the above was simple. The reason I was connecting this to an action using Vala in the first place was because the `@Gtk.Callback()` were not recognized, it seems to only look in the Vala scope, likely because that's where the Gtk template is set from the ui file.  However, instead of using callbacks, simply connecting them is a simple workaround, and solves the above issue with the crash that I described earlier. So now it all works as expected.

**Comment by Sjoerd1993** [comment]
See attached video. I've also added an "Y=" label in front of the equations. While a lowercase letter looks somewhat nicer in this particular situation imo, I used an uppercase for consistency's sake with the rest of the program.

It would perhaps be cleaner to use `f(x)=`, especially now there's more variables. But again I kept it as `Y=` for consistency's sake. We could change the Add Equation dialog to `f(x)` as well. But I was a bit unsure if that needed changing at all.

**Comment by Sjoerd1993** [comment]
My final change to this PR, I've also changed the wording for the standard deviations, so that it now also provides the confidence interval according to the [68-95-99.7 rule](https://en.wikipedia.org/wiki/68%E2%80%9395%E2%80%9399.7_rule). I think the certainty is a measure that many are interested in, and if I recall correctly is the measure that Matlab also shows rather than the standard deviation. I did have to shorten "Standard Deviation"  to SD though. Which is common, but maybe slightly too jargon for some...? Although people who won't recognize that won't really recognize "Standard deviation" either, and are more helped with the certainty wording was my reasoning there.

image

**Comment by Sjoerd1993** [comment]
On the latest changes, here's SciPy about the optimization methods:

```
method{‘trf’, ‘dogbox’, ‘lm’}, optional

    Algorithm to perform minimization.

            ‘trf’ : Trust Region Reflective algorithm, particularly suitable for large sparse problems with bounds. Generally robust method.

            ‘dogbox’ : dogleg algorithm with rectangular trust regions, typical use case is small problems with bounds. Not recommended for problems with rank-deficient Jacobian.

            ‘lm’ : Levenberg-Marquardt algorithm as implemented in MINPACK. Doesn’t handle bounds and sparse Jacobians. Usually the most efficient method for small unconstrained problems.

```

So Levenberg-Marquardt doesn't handle bounds, hence hiding them when selected. And in general `trf` seems by far the most obvious choice as default option.

**Review by cmkohnen — APPROVED** [review]

**Pull request merged**
