### PR TITLE
Prevent view menu from stealing focus

### PR DESCRIPTION
**Pull request by Sjoerd1993**
See title. When scaling is changed through the view menu, the focus is changed to the view menu. Making it impossible to use shortcuts. This fixes this.

### CODE REVIEW

**Comment by Sjoerd1993** [comment]
Just realized that this does make it impossible to reach the view menu using keyboard navigation, so maybe we need a slightly more clever solution. Perhaps try and see if we can drop the focus after a scale change (it seems to be the only the radio buttons that steal focus). 

Keyboard navigation is a bit clunky anyway and not really something I'd recommend, but it's one of the GNOME Circle Accesibility requirements. So probably should rethink this: 

>  [Can navigate to all elements via keyboard and use them](https://gitlab.gnome.org/Teams/Releng/AppOrganization/-/blob/main/AppCriteria.md)

**Comment by Sjoerd1993** [comment]
This works, it's somewhat of a workaround, but this forces to set the focus to the toast overlay after changing the axis limits. Which solves the issue adressed in this PR, without losing keyboard navigation.

**Review by cmkohnen — APPROVED** [review]
This deviates from the formatting we have going a little bit (which makes it a bit harder to understand which parentheses begins and ends where). But I'm fine with that.

**Comment by Sjoerd1993** [comment]
> This deviates from the formatting we have going a little bit (which makes it a bit harder to understand which parentheses begins and ends where). But I'm fine with that.

Yeah, feel free to change the formatting a bit in a future PR. It was a bit tricky to format it such that the linter approved, especially with the relatively long calls. Was tempted to just define a separate function here instead of using the lambda, but this worked.

**Pull request merged**
