### PR TITLE
make the source to . so that the branches can also be tested

### PR DESCRIPTION
**Pull request by soumyaDghosh**

### CODE REVIEW

**Comment by soumyaDghosh** [comment]
kindly merge this asap. @Sjoerd1993 

I will be able to test the snap then.

**Review by Sjoerd1993 — APPROVED** [review]

**Comment by Sjoerd1993** [comment]
Just as an fyi, the failing `flake8` test seems to be an upstream issue, due to a module being updated that is now incompatible. So that's not an issue with this particular change.

**Comment by soumyaDghosh** [comment]
@Sjoerd1993 am I missing any typelib file?

```
  File "/snap/graphs/83/usr/bin/graphs", line 40, in <module>
    gi.require_version("Graphs", "1")
  File "/snap/graphs/83/gnome-platform/usr/lib/python3/dist-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Graphs not available
```

**Comment by Sjoerd1993** [comment]
The Graphs namespace is declared using the Vala code of the main application, and installed in meson in `src`. 

I am not exactly sure where this is going wrong based on the code snippet up here, but perhaps this here helps (from `meson.build` in `src`)

```
graphs_lib = shared_library(
  'graphs',
  files(
    'application.vala',
    'curve_fitting.vala',
    'data.vala',
    'figure_settings.vala',
    'interfaces.vala',
    'item.vala',
    'inline-stack-switcher.vala',
    'misc.vala',
    'preferences.vala',
    'utilities.vala',
    'window.vala',
  ), blueprints_hack, gresource_bundle,
      vala_gir: 'Graphs-1.gir',
  dependencies: dependencies,
       install: true,
   install_dir: [true],
)

custom_target('graphs typelib',
       command: [find_program('g-ir-compiler'), '--shared-library', 'libgraphs.so', '--output', '@OUTPUT@', meson.current_build_dir() / 'Graphs-1.gir'],
        output: 'Graphs-1.typelib',
       depends: graphs_lib,
       install: true,
   install_dir: get_option('libdir') / 'girepository-1.0')
```

**Comment by soumyaDghosh** [comment]
Yup, I actually filtered, which files to be allowed. Removed that.

**Pull request merged**
