### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Graphs/graphs](https://hosted.weblate.org/projects/graphs/graphs/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by Sjoerd1993** [comment]
This is just a minor translation update, mostly to check whether the Weblate PR integration is working. 
Seems it is. 

Will try to see if I can get the changelogs out of the Translation percent status. Or perhaps keep it there, but see if I can categorize it somehow.

**Review by Sjoerd1993 — APPROVED** [review]

**Comment by Sjoerd1993** [comment]
Made some more changes to the translations, updated the Swedish and the Dutch translations now fully to the latest build. Weblate automatically generates "Strings marked for edit" which contains all strings were the source have been changed. 

The nice thing is that any changes now to the Weblate template are pushed as a commit to the latest PR. So when adding new changes, and a Weblate PR is already open, it doesn't create a new PR.

There's a few strings where the complete wrong translation was carried over. This is likely the case for Turkish as well, so we should try and see if those can get fixed before the next release. If e.g. @sabriunal doesn't have the time to help us out with those, I can probably remove the strings that are definitely wrong.

**Review by cmkohnen — APPROVED** [review]

**Comment by cmkohnen** [comment]
> I also found it is possible to automatically do machine translations on missing strings in Weblate, and then mark those ad "Need editing". But I am not really convinced yet that is the way to go. Still, it is a bit like choosing between awkward localized translations, or english translations for unfinished localized strings. So I can see arguments for both.

Does machine translation mean something like Google Translate?

**Comment by Sjoerd1993** [comment]
> Does machine translation mean something like Google Translate?

The default API uses [LibreTranslate](https://libretranslate.com/), which seems to be simular to Google Translate yes but FOSS. It's not too bad for "placeholder" things in general, but the main disadvantage is that it's not really context-aware.

A good thing is that it does give a confidence rating, and you can set up Weblate such that it only sets a "placeholder translation" like that if a confidence level of 80 is reached. However, due to it's lack of context-awareness, it can go pretty wrong as well. For instance "Translate X" gets translated into Swedish as "Översätt X" (Översätt means translate as in convert to a different language). Which is very wrong, but as it's a perfectly good translation out of context, it gets a pretty high confidence rating. So that measure is not perfect either.
The main question is what would be preferred. Having the risk of having some awkward translations at places when things are moving fast, or having those strings be in the wrong language but with the correct meaning. 

Such automated strings are flagged as "Need editing", and are _not_ counted towards the total translated percentage by the way. So they are still flagged as unfinished, and therefore exposed to contributors as needing work. It's mainly a question about the placeholders.

The main strings that are generally not translated (and are therefore affected by such a setting) are changelists, and new strings in languages that I absolutely do not know. I try to keep the Dutch and Swedish translations updated myself. I know some German, so I could probably at least see when things are completely off if we'd get a German translation at one point. But in e.g. Turkish it could contain a recipe to bake bread in the translations, and I still wouldn't notice.

**Comment by Sjoerd1993** [comment]
But short answer is yes, the translation seems to be something similar to Google Translate. 
On a side-note, I should have given you an invite to Weblate as an administrator role. Just so you have access to these things as well.

**Comment by sabriunal** [comment]
"If e.g. @sabriunal doesn't have the time to help us out with those, I can probably remove the strings that are definitely wrong."

Which strings are they? I'll check tonight.

**Comment by cmkohnen** [comment]
My suggestion would be to wait for the Circle application and hopefully we can confidently keep the current strings (and only add new ones as new features are added).

**Comment by Sjoerd1993** [comment]
> Which strings are they? I'll check tonight.

Thanks a lot, it's really appreciated. The translation is now all hosted on Weblate, which can be found [here](https://hosted.weblate.org/projects/graphs/graphs/tr/).
The strings that need checking are the ones that have a `Strings marked for edit`  category (direct link [here](https://hosted.weblate.org/browse/graphs/graphs/tr/?q=state:needs-editing)). Basically it includes all the strings that have been changed/updated. 
In most cases the original translation is probably still completely fine. But there's a few cases where it now has the wrong translation for a string. This is likely the result of things being reordered around, after which gettext got confused.  

> LibreTranslate works horrible for Turkish.

Thanks for your input, I only checked quickly for the languages I'm familiar with, and it seemed similar to Google Translate. I think I'll keep it to add an automated suggestion, but keep the string itself blank. 

> My suggestion would be to wait for the Circle application and hopefully we can confidently keep the current strings (and only add new ones as new features are added).

Indeed, I think it's good to keep it as-is. At the moment it _should_ offer suggestions when doing translations. But the strings themselves are still kept blank, so it's there to serve as hint for the contributor. In principle changing the current strings somewhat shouldn't be an issue. It just means that these strings end up in this mentioned "marked for edit" category. But with more major changes things can break. (I think with the redesign of the preference window this happened).

**Pull request merged**
